### ISSUE TITLE
Rephrasing required & other errors

### ISSUE THREAD

**Issue by DanielvanVliet** [wouter-swierstra/logic-notes#6]
These are phrasing errors of which i'm not entirely sure of how to fix them

- "To prove soundness and completeness requires is not easy" -  (Relating natural deduction and semantics)
- "We will write use the following notation"   -  (Operational semantics)

Other errors you might want to double check:

In the answers of 3.12 the reorganized proof should have the initial program p1;(p2;p3)

Near the end of Case study: gcd
gcd(x,y) = gcd(x - y, x)
should be:
gcd(x,y) = gcd(x - y, _**y**_)

**Comment by wouter-swierstra** [comment]
Thanks Daniel -- I'll fix these and push the changes.

  Wouter

________________________________________
